#!/usr/bin/env python3
"""Generate a deterministic Markdown inventory of the public Python API."""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path
from typing import Optional


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "flyto_pro_core"
OUTPUT = ROOT / "docs" / "reference" / "python-api.md"


def annotation(node: Optional[ast.expr]) -> str:
    """Render one AST type annotation."""
    if node is None:
        return ""
    return ast.unparse(node)


def signature(node: ast.FunctionDef | ast.AsyncFunctionDef, *, method: bool) -> str:
    """Render one public function or method signature."""
    args = node.args
    parts: list[str] = []
    positional = [*args.posonlyargs, *args.args]
    defaults = [None] * (len(positional) - len(args.defaults)) + list(args.defaults)
    for arg, default in zip(positional, defaults):
        if method and arg.arg in {"self", "cls"}:
            continue
        value = arg.arg
        if arg.annotation:
            value += f": {annotation(arg.annotation)}"
        if default is not None:
            value += f" = {ast.unparse(default)}"
        parts.append(value)
    if args.vararg:
        parts.append(f"*{args.vararg.arg}")
    elif args.kwonlyargs:
        parts.append("*")
    for arg, default in zip(args.kwonlyargs, args.kw_defaults):
        value = arg.arg
        if arg.annotation:
            value += f": {annotation(arg.annotation)}"
        if default is not None:
            value += f" = {ast.unparse(default)}"
        parts.append(value)
    if args.kwarg:
        parts.append(f"**{args.kwarg.arg}")
    prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
    result = f"{prefix}{node.name}({', '.join(parts)})"
    if node.returns:
        result += f" -> {annotation(node.returns)}"
    return result


def summary(node: ast.AST, owner: Optional[str] = None) -> str:
    """Extract the first sentence of a public symbol docstring."""
    doc = ast.get_docstring(node)
    if not doc:
        name = getattr(node, "name", "symbol")
        qualified = f"{owner}.{name}" if owner else name
        raise ValueError(f"public symbol lacks a docstring: {qualified}")
    return " ".join(doc.strip().splitlines()).split(". ", 1)[0].rstrip(".") + "."


def render() -> str:
    """Render the complete generated Python API reference."""
    lines = [
        "# Python API Reference",
        "",
        "> Generated by `python scripts/generate-api-reference.py`. Do not edit manually.",
        "",
        "This inventory covers every public top-level class and function and every",
        "public method declared in `src/flyto_pro_core`. Underscore-prefixed helpers",
        "remain implementation details. See package `__init__.py` files for preferred",
        "convenience imports.",
        "",
    ]
    for path in sorted(SOURCE.rglob("*.py")):
        if path.name == "__init__.py":
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"))
        public = [
            node
            for node in tree.body
            if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))
            and not node.name.startswith("_")
        ]
        if not public:
            continue
        module = ".".join(path.relative_to(SOURCE.parent).with_suffix("").parts)
        source = path.relative_to(ROOT).as_posix()
        lines.extend([f"## `{module}`", ""])
        for node in public:
            if isinstance(node, ast.ClassDef):
                bases = ", ".join(ast.unparse(base) for base in node.bases)
                declaration = f"class {node.name}" + (f"({bases})" if bases else "")
                lines.extend(
                    [
                        f"### `{node.name}`",
                        "",
                        f"`{declaration}`",
                        f"Source: [`{source}`](../../{source}#L{node.lineno})",
                        "",
                        summary(node),
                        "",
                    ]
                )
                methods = [
                    item
                    for item in node.body
                    if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))
                    and not item.name.startswith("_")
                ]
                if methods:
                    lines.extend(["| Method | Purpose |", "|---|---|"])
                    for method in methods:
                        sig = signature(method, method=True).replace("|", "\\|")
                        purpose = summary(method, node.name).replace("|", "\\|")
                        lines.append(
                            f"| [`{sig}`](../../{source}#L{method.lineno}) | {purpose} |"
                        )
                    lines.append("")
            else:
                sig = signature(node, method=False)
                lines.extend(
                    [
                        f"### `{node.name}`",
                        "",
                        f"[`{sig}`](../../{source}#L{node.lineno})",
                        "",
                        summary(node),
                        "",
                    ]
                )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    """Run this maintenance or integration script."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT.relative_to(ROOT)} is stale", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
