name: Documentation

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  contract:
    uses: flytohub/.github/.github/workflows/reusable-documentation.yml@423fe8478c8b7e3d9481c61c65fc3d8e734fac5f
